### ISSUE TITLE
Emotes not listed in ".e list"

### ISSUE THREAD

**Issue by DarkConqueror2002** [wootguy/emotes#7]
Heya w00tguy. This isn't really a issue but more of a question. On some servers I see people use emotes not listed under .e list and searched everywhere on the internet to no avail and even here to no avail. Question is how do I find those custom emotes? Thanks. Btw love your work, makes servers much more fun.

**Comment by wootguy** [comment]
You can make your own with this command:
`.e <sequence> [mode] [speed] [start_frame] [end_frame]"`

so, for example:
`.e 15 freeze 0.5`
would play a death animation at 50% speed and stop at the last frame. More info is in the [readme](https://github.com/wootguy/emotes/blob/master/README.md).

Some models have special animations which you can see in the model viewer [here](https://wootguy.github.io/scmodels/).

**Comment by DarkConqueror2002** [comment]
> You can make your own with this command:
> `.e <sequence> [mode] [speed] [start_frame] [end_frame]"`
> 
> so, for example:
> `.e 15 freeze 0.5`
> would play a death animation at 50% speed and stop at the last frame. More info is in the [readme](https://github.com/wootguy/emotes/blob/master/README.md).
> 
> Some models have special animations which you can see in the model viewer [here](https://wootguy.github.io/scmodels/).

Hi thanks for the reply w00tguy. The custom emote part where you set the speed, sequence, etc I am pretty much solid on. I am just having trouble with the special animation part. When I look at the special animation name like for example "dab" when I type .e dab in the console it says emote is not recognized but its part of the characters animation sequence. Thanks for the help w00tguy it made my day!

**Comment by wootguy** [comment]
> When I look at the special animation name like for example "dab" when I type .e dab in the console it says emote is not recognized but its part of the characters animation sequence. 

You have to to use the sequence number in the model viewer to select special animations. The name of the animation can't be used. The `.e list` names are what I coded into the plugin and are unrelated to the animation names built into the model.
